export const siteOptions = [
    { value: "", label: "Select an option", disabled: true, selected: true },
    { value: "building", label: "Building" },
    { value: "library", label: "Library" },
    { value: "hotel", label: "Hotel" },
    { value: "stadium", label: "Stadium" },
    { value: "restaurant", label: "Restaurant" },
    { value: "school", label: "School" },
    { value: "apartment", label: "Apartment" },
    { value: "park", label: "Park" },
    { value: "mall", label: "Mall" },
    { value: "office", label: "Office" },
    { value: "factory", label: "Factory" },
    { value: "airport", label: "Airport" },
    { value: "hospital", label: "Hospital" },
    { value: "supermarket", label: "Supermarket" },
    { value: "bank", label: "Bank" },
    { value: "highway", label: "Highway" },
    { value: "warehouse", label: "Warehouse" },
    { value: "amusement park", label: "Amusement park" },
    { value: "church", label: "Church" },
    { value: "museum", label: "Museum" },
    { value: "shopping center", label: "Shopping center" },
    { value: "oil rig", label: "Oil rig" },
    { value: "power plant", label: "Power plant" },
    { value: "city street", label: "City street" },
    { value: "bridge", label: "Bridge" },
    { value: "river", label: "River" },
    { value: "forest", label: "Forest" },
    { value: "office building", label: "Office building" },
    { value: "high-rise building", label: "High-rise building" }
  ];

export const typeOptions = [
    { value: "", label: "Select an option", disabled: true, selected: true },
    { value: "fire", label: "Fire" },
    { value: "flood", label: "Flood" },
    { value: "traffic accident", label: "Traffic Accident" },
    { value: "accident", label: "Accident" },
    { value: "collapse", label: "Collapse" },
    { value: "terrorist activity", label: "Terrorist Activity" },
    { value: "explosion", label: "Explosion" },
    { value: "chemical hazard", label: "Chemical Hazard" },
    { value: "tornado", label: "Tornado" },
    { value: "earthquake", label: "Earthquake" },
    { value: "hurricane", label: "Hurricane/Storm" },
    { value: "wildfire", label: "Wildfire" },
];
  